/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import java.awt.Color;

/**
 *
 * @author Domenica Cañizares
 */
public class JuegoTresEnRaya extends javax.swing.JFrame {

    /**
     * Creates new form JuegoTresEnRaya
     */
    public JuegoTresEnRaya() {
        initComponents();
        pnlO.setBackground(Color.green);
        pnlX.setBackground(Color.yellow);

        //lineas horizontales
        ho11.setVisible(false);
        hor2.setVisible(false);
        hor3.setVisible(false);

        //lineas verticales
        ver1.setVisible(false);
        ver2.setVisible(false);
        ver3.setVisible(false);

        //lineas horizontales
        dia1.setVisible(false);
        dia2.setVisible(false);
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    
    

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dia1 = new javax.swing.JLabel();
        dia2 = new javax.swing.JLabel();
        ho11 = new javax.swing.JPanel();
        hor2 = new javax.swing.JPanel();
        hor3 = new javax.swing.JPanel();
        ver1 = new javax.swing.JPanel();
        ver2 = new javax.swing.JPanel();
        ver3 = new javax.swing.JPanel();
        btn00 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn01 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn02 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bttNuevo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pnlX = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jX1 = new javax.swing.JLabel();
        pnlO = new javax.swing.JPanel();
        jO1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dia1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/raya 1.png"))); // NOI18N
        dia1.setText("  ");
        jPanel1.add(dia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 20, 1020, 280));

        dia2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/raya 2.png"))); // NOI18N
        dia2.setText("jLabel7");
        jPanel1.add(dia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -70, 370, 370));

        ho11.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout ho11Layout = new javax.swing.GroupLayout(ho11);
        ho11.setLayout(ho11Layout);
        ho11Layout.setHorizontalGroup(
            ho11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        ho11Layout.setVerticalGroup(
            ho11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        jPanel1.add(ho11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 310, -1));

        hor2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout hor2Layout = new javax.swing.GroupLayout(hor2);
        hor2.setLayout(hor2Layout);
        hor2Layout.setHorizontalGroup(
            hor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        hor2Layout.setVerticalGroup(
            hor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        jPanel1.add(hor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 310, -1));

        hor3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout hor3Layout = new javax.swing.GroupLayout(hor3);
        hor3.setLayout(hor3Layout);
        hor3Layout.setHorizontalGroup(
            hor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        hor3Layout.setVerticalGroup(
            hor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        jPanel1.add(hor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 310, -1));

        ver1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout ver1Layout = new javax.swing.GroupLayout(ver1);
        ver1.setLayout(ver1Layout);
        ver1Layout.setHorizontalGroup(
            ver1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        ver1Layout.setVerticalGroup(
            ver1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jPanel1.add(ver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 10, 280));

        ver2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout ver2Layout = new javax.swing.GroupLayout(ver2);
        ver2.setLayout(ver2Layout);
        ver2Layout.setHorizontalGroup(
            ver2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        ver2Layout.setVerticalGroup(
            ver2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jPanel1.add(ver2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        ver3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout ver3Layout = new javax.swing.GroupLayout(ver3);
        ver3.setLayout(ver3Layout);
        ver3Layout.setHorizontalGroup(
            ver3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        ver3Layout.setVerticalGroup(
            ver3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jPanel1.add(ver3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        btn00.setActionCommand("");
        btn00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn00ActionPerformed(evt);
            }
        });
        jPanel1.add(btn00, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 36, 81, 68));

        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });
        jPanel1.add(btn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 122, 81, 68));

        btn01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn01ActionPerformed(evt);
            }
        });
        jPanel1.add(btn01, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 36, 81, 68));

        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });
        jPanel1.add(btn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 122, 81, 68));

        btn02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn02ActionPerformed(evt);
            }
        });
        jPanel1.add(btn02, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 36, 81, 68));

        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });
        jPanel1.add(btn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 122, 81, 68));

        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });
        jPanel1.add(btn20, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 208, 81, 68));

        btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn21ActionPerformed(evt);
            }
        });
        jPanel1.add(btn21, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 208, 81, 68));

        btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn22ActionPerformed(evt);
            }
        });
        jPanel1.add(btn22, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 208, 81, 68));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 106, 325, 296));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("Juego Tres en raya");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        bttNuevo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bttNuevo.setText("Jugar otra vez");
        bttNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(bttNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 120, 163, 51));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("X");

        jX1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jX1.setText("0");

        javax.swing.GroupLayout pnlXLayout = new javax.swing.GroupLayout(pnlX);
        pnlX.setLayout(pnlXLayout);
        pnlXLayout.setHorizontalGroup(
            pnlXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlXLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jX1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlXLayout.setVerticalGroup(
            pnlXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlXLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jX1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addContainerGap())
        );

        jO1.setBackground(new java.awt.Color(255, 255, 255));
        jO1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jO1.setText("0");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("O");

        javax.swing.GroupLayout pnlOLayout = new javax.swing.GroupLayout(pnlO);
        pnlO.setLayout(pnlOLayout);
        pnlOLayout.setHorizontalGroup(
            pnlOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jO1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlOLayout.setVerticalGroup(
            pnlOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jO1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(pnlX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 189, -1, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 88, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
// iniciar variables
    private int matriz[][] = new int[3][3];
    
    public void ingresar(){
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                matriz[i][j]=(j+10)*(i+10);
            }
        }
    }
    
    Contenido cont = new Contenido(0, 0, 0);
    
    public void opcion(){
        if(cont.getTurno()==1){
            pnlX.setBackground(Color.yellow);
            pnlO.setBackground(Color.green);
        }
        if(cont.getTurno()==0){
            pnlX.setBackground(Color.green);
            pnlO.setBackground(Color.yellow);
        }
    }
    
    public void nuevo(){
        ingresar();
        btn00.setText("");
        btn00.setEnabled(true);
        
        btn01.setText("");
        btn01.setEnabled(true);
        
        btn02.setText("");
        btn02.setEnabled(true);
        
        btn10.setText("");
        btn10.setEnabled(true);
        
        btn11.setText("");
        btn11.setEnabled(true);
        
        btn12.setText("");
        btn12.setEnabled(true);
        
        btn20.setText("");
        btn20.setEnabled(true);
        
        btn21.setText("");
        btn21.setEnabled(true);
        
        btn22.setText("");
        btn22.setEnabled(true);
        
        //lineas horizontales
        ho11.setVisible(false);
        hor2.setVisible(false);
        hor3.setVisible(false);

        //lineas verticales
        ver1.setVisible(false);
        ver2.setVisible(false);
        ver3.setVisible(false);

        //lineas horizontales
        dia1.setVisible(false);
        dia2.setVisible(false);
    }
    
    private void btn00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn00ActionPerformed
        opcion();
        //diagonal
        cont.rayar(matriz, dia1, 7, 0, 0);
        //horizontal
        cont.rayar(matriz, ho11, 1, 0, 0);
        //vertical
        cont.rayar(matriz, ver1, 4, 0, 0);
        
        if(cont.jugar(btn00, 0, 0, matriz, jX1, jO1)==1){
             
        }
    }//GEN-LAST:event_btn00ActionPerformed
                                  
    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        opcion();
        //horizontal
        cont.rayar(matriz, hor2, 2, 1, 0);
        //vertical
        cont.rayar(matriz, ver1, 4, 1, 0);
        
        if(cont.jugar(btn10, 1, 0, matriz, jX1, jO1)==1){
             
        }
    }//GEN-LAST:event_btn10ActionPerformed
    
    
    private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ActionPerformed
         //horizontal
        cont.rayar(matriz, hor3, 3, 2, 0);
        //vertical
        cont.rayar(matriz, ver1, 4, 2, 0);
        //diagonal
        cont.rayar(matriz, dia2, 8, 2, 0);
        
        if(cont.jugar(btn20, 2, 0, matriz, jX1, jO1)==1){
             
        }
    }//GEN-LAST:event_btn20ActionPerformed

    private void btn01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn01ActionPerformed
        opcion();
        //horizontal
        cont.rayar(matriz, ho11, 1, 0, 1);
        //vertical
        cont.rayar(matriz, ver2, 5, 0, 1);
        
        if(cont.jugar(btn01, 0, 1, matriz, jX1, jO1)==1){
             
        }
    }//GEN-LAST:event_btn01ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        opcion();
        
        //diagonal
        cont.rayar(matriz, dia1, 7, 1, 1);
        cont.rayar(matriz, dia2, 8, 1, 1);
        //horizontal
        cont.rayar(matriz, hor2, 2, 1, 1);
        //vertical
        cont.rayar(matriz, ver2, 5, 1, 1);
        
        if(cont.jugar(btn11, 1, 1, matriz, jX1, jO1)==1){
             
        }
        
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn22ActionPerformed
        opcion();
        //diagonal
        cont.rayar(matriz, dia1, 7, 2, 2);
        //horizontal
        cont.rayar(matriz, hor3, 3, 2, 2);
        //vertical
        cont.rayar(matriz, ver3, 6, 2, 2);
        
        if(cont.jugar(btn22, 2, 2, matriz, jX1, jO1)==1){
             
        }
    }//GEN-LAST:event_btn22ActionPerformed

    private void btn02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn02ActionPerformed
        opcion();
        //horizontal
        cont.rayar(matriz, ho11, 1, 0, 2);
        //vertical
        cont.rayar(matriz, ver3, 6, 0, 2);
        //diagonal
        cont.rayar(matriz, dia2, 8, 0, 2);
        
        if(cont.jugar(btn02, 0, 2, matriz, jX1, jO1)==1){
             
        }
    }//GEN-LAST:event_btn02ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        opcion();
        //horizontal
        cont.rayar(matriz, hor2, 2, 1, 2);
        //vertical
        cont.rayar(matriz, ver3, 6, 1, 2);
        
        if(cont.jugar(btn12, 1, 02, matriz, jX1, jO1)==1){
             
        }
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn21ActionPerformed
        opcion();
        //horizontal
        cont.rayar(matriz, hor3, 3, 2, 1);
        //vertical
        cont.rayar(matriz, ver2, 5, 2, 1);
        
        if(cont.jugar(btn21, 2, 1, matriz, jX1, jO1)==1){
             
        }
    }//GEN-LAST:event_btn21ActionPerformed

    private void bttNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttNuevoActionPerformed
        nuevo();
    }//GEN-LAST:event_bttNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoTresEnRaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoTresEnRaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoTresEnRaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoTresEnRaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoTresEnRaya().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn00;
    private javax.swing.JButton btn01;
    private javax.swing.JButton btn02;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton bttNuevo;
    private javax.swing.JLabel dia1;
    private javax.swing.JLabel dia2;
    private javax.swing.JPanel ho11;
    private javax.swing.JPanel hor2;
    private javax.swing.JPanel hor3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jO1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jX1;
    private javax.swing.JPanel pnlO;
    private javax.swing.JPanel pnlX;
    private javax.swing.JPanel ver1;
    private javax.swing.JPanel ver2;
    private javax.swing.JPanel ver3;
    // End of variables declaration//GEN-END:variables
}
